Renamed $title to $track in ripDisc(). Minor tweaks.

diff --git a/rip b/rip
--- a/rip
+++ b/rip
@@ -56,14 +56,14 @@ function sanitiseFilePath ()
 }
 
 function ripDisc ()
-# Invokes rip() on $1 specifying which titles to rip from atomicMetadata…(), autotagTrack() on each track, then tar(1)s and moves dvdmedia to trash.
+# Invokes rip() on $1 specifying which titles to rip from atomicMetadata, autotagTrack() on each track, then tar(1)s and moves dvdmedia to trash.
 # Uses rip()
 # Uses autotagTrack()
 # Uses del #trash
 # Uses defaultsReadAtomicMetadata()
 {
     local dvdmedia="$1" \
-          title
+          track
 
     local ALBUM="$(defaultsReadAtomicMetadata "$dvdmedia" Album album)" \
           DISK="$(defaultsReadAtomicMetadata "$dvdmedia" Disc disk)" \
@@ -76,15 +76,16 @@ function ripDisc ()
     else
         filepath="./${ALBUM}/${ALBUM}: Disc ${DISK}"
     fi
-    #TODO:FIXME: Use the name of the "feature" for the subfolder, not merely "disc 2"?
     mkdir -p "./${filepath}"
 
-    for title in $(defaultsReadAtomicMetadata "$dvdmedia" Disc trackList)
+    for track in $(defaultsReadAtomicMetadata "$dvdmedia" Disc trackList)
     do
-        FILE="${filepath}/${VOLUME}-${title}.m4v"
+        FILE="${filepath}/${VOLUME}-${track}.m4v" # Imitate HandBrake file naming.
+        #FILE="${filepath}/${DISK}-${track} ${trackName}.m4v" # Imitate iTunes file naming.
 
-        time rip "${dvdmedia}" "$title" "$FILE" && \
-        autotagTrack "${dvdmedia}" "$title" "$FILE" || return # short-circuit if something fails
+        time rip "$dvdmedia" "$track" "$FILE" \
+        && \
+        autotagTrack "$dvdmedia" "$track" "$FILE" || return # short-circuit if something fails
     done
 
     ripGrowl "${ALBUM}: Disc ${DISK}." "$VOLUME"
