Complete initial implementation of newRip(). Ready to replace rip(). Needs testing. Implemented ripSanity(), ripFail(), ripUsage(), ripParseAudioNames(), ripParseAudioTracks().

diff --git a/rip b/rip
--- a/rip
+++ b/rip
@@ -205,6 +205,97 @@ function ripChapters ()
     done
 }
 
+function ripSanity () 
+{
+    if ! test -d "${1}/VIDEO_TS"
+    then
+        echo "rip(): The first argument must be the full path to a DVDMedia bundle." 1>&2
+        echo "       See initDVDMedia()." 1>&2
+        ripUsage
+        return -1
+    fi
+
+    if test 0 -eq "$2" || test ! 0 -ne "$2"
+    # This test is intended to check whether $2 is an integer.
+    then
+        echo "rip(): The second argument must be an integer specifying which title to encode." 1>&2
+        ripUsage
+        return -2
+    fi
+    
+    if [ x"${whichChapters#*:}" == x"${whichChapters%%:*}" ]
+    then
+        echo "rip(): The third argument, if specified, must match the form 'string:integer-range'." 1>&2
+        ripUsage
+        return -3
+    fi
+}
+
+function ripFail () 
+{
+    RET="${?:-0}" # Preserve the return value.
+
+    if [ x"$1" == x"audioList" ] || [ x"$1" == x"subtitleList" ] || [ x"$1" == x"UDFVolumeName" ]
+    then
+        echo "rip(): Unable to read '$1' from atomicMetadata." 1>&2
+        echo "       See initDVDMedia()." 1>&2
+    else if [ x"$1" == x"ripParseAudioNames" ] || [ x"$1" == x"ripParseAudioTracks" ]
+    then
+        echo "rip(): Unable to parse '${2}List' (from atomicMetadata)." 1>&2
+    else if [ x"$1" == x"HandBrakeCLI" ]
+    then
+        echo "rip(): HandBrake has failed to complete successfully." 1>&2
+    fi
+    fi
+    fi
+
+    ripUsage
+    return "$RET";
+}
+
+function ripParseAudioNames ()
+# Code duplication with ripParseAudioTracks().
+{
+    if [ x"$1" == x"" ] || [ x"$1" == x"_TAG_audioList_PLACEHOLDER_" ]
+    then
+        return -1
+    fi
+
+    local AUDIO_LIST="$1" \
+          audio_track \
+          IFS="," # Overriding IFS is ugly, bug efficient. Local'd so that it doesn't damage other stuff.
+    for audio_track in $AUDIO_LIST
+    do
+        echo -n "${audio_track#*:},"
+            # What audio tracks to encode
+            # TODO: FIXME: Untested
+    done
+}
+
+function ripParseAudioTracks () 
+# Code duplication with ripParseAudioNames().
+{
+    if [ x"$1" == x"" ] || [ x"$1" == x"_TAG_audioList_PLACEHOLDER_" ]
+    then
+        return -1
+    fi
+
+    local AUDIO_LIST="$1" \
+          audio_track \
+          IFS="," # Overriding IFS is ugly, bug efficient. Local'd so that it doesn't damage other stuff.
+    for audio_track in $AUDIO_LIST
+    do
+        echo -n "${audio_track%:*},"
+            # What audio tracks to encode
+            # TODO: FIXME: Untested
+    done
+}
+
+function ripUsage () 
+{
+    echo "Usage: rip /path/to/DVD_VIDEO.dvdmedia 2 [ep1:1-4]" 1>&2
+}
+
 function newRip ()
 # rip() /path/to/VIDEO_TS/.. 7
 {
@@ -212,24 +303,24 @@ function newRip ()
     local whichTrack="$2" # integer
     local whichChapters="${3:-}" # 1:1-4 or highlights:2-5,7,13
     
-    ripSanity "$dvdmedia" "$whichTrack" || ripFail "ripSanity"
+    ripSanity "$dvdmedia" "$whichTrack" "$whichChapters" || return
 
-    local audioList="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" audioList)" || ripFail "audioList"
-    local subtitleList="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" subtitleList)" || ripFail "subtitleList"
+    local audioList="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" audioList)" || ripFail "audioList" || return
+    local subtitleList="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" subtitleList)" || ripFail "subtitleList" || return
 
-    local DVDNAME="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" UDFVolumeName)" || ripFail "UDFVolumeName"
+    local DVDNAME="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" UDFVolumeName)" || ripFail "UDFVolumeName" || return
         # Use $DVDNAME as the base name for the output file (see $FILE below).
 
     local chapterList="${whichChapters#*:}" # everything after the first colon
     local chapterName="${whichChapters%%:*}" # everything before the first colon
         # There should only be one colon. 
-        #TODO:FIXME: Chapter name should be extracted from $dvdmedia/chapters-$whichTrack.txt
+        # $chapterName is not the name of the _one_ chapter to be encoded, but the name of the _set_ of chapters to be encoded.
 
-    local audioNames="$(ripParseAudioNames "$audioList")"
-    local audioTracks="$(ripParseAudioTracks "$audioList")"
-    
-    local subtitleNames="$(ripParseAudioNames "$subtitleList")"
-    local subtitleTracks="$(ripParseAudioTracks "$subtitleList")"
+    local audioNames="$(ripParseAudioNames "$audioList")" || ripFail "ripParseAudioNames" "audio" || return
+    local audioTracks="$(ripParseAudioTracks "$audioList")" || ripFail "ripParseAudioTracks" "audio" || return
+
+    local subtitleNames="$(ripParseAudioNames "$subtitleList")" || ripFail "ripParseAudioNames" "subtitle" || return
+    local subtitleTracks="$(ripParseAudioTracks "$subtitleList")" || ripFail "ripParseAudioTracks" "subtitle" || return
 
     FILE="${DVDNAME}-${whichTrack}${chapterName:+-}${chapterName:-}.m4v"
         # e.g. DVD_VIDEO-1-Triumph.m4v
@@ -253,7 +344,7 @@ function newRip ()
         --aencoder "$(IFS=,; for i in $audioTracks; do echo -n ca_aac,; done)" \
         "${audioNames:+--aname}" "${audioNames:-}" \
         "${SPECIAL_RIP_OPTIONS[@]}" \
-    2>> ~/Library/Logs/net.gaelicWizard.rip/"$DVDNAME".log ) || return
+    2>> ~/Library/Logs/net.gaelicWizard.rip/"$DVDNAME".log ) || ripFail "HandBrakeCLI" || return
         # Universal preset to activate sensible defaults.
         # Use the longest title, if none specified.
         # Only encode selected chapters, if specified.
@@ -290,9 +381,6 @@ function newRip ()
         
         #Tag some basic housekeeping
         tag "${FILE}" --album "$DVDNAME" "${TRACK:+--track}" "$TRACK"
-    else
-        echo "$FUNCNAME: ${FILE} does not appear to have been created." 1>&2
-        return -2
     fi
     
     addRipOptions # If any SPECIAL_RIP_OPTIONS are set, then issue a warning.
