Comments. Minor alterations to ripDisc()'s filename generation. Deprecate ripBleachOld(). Improve usage statement for defaultsReadAtomicMetadatas(). Remove ripTitles(), unused and deprecated (logic previously merged into ripDisc()). Remove ripAnglesOld(), never worked. To be re-implemented by same mechanism as ripChapters(). Remove ripChapters(), no longer worked. To be re-implemented through creative use of atomicMetadata. Update ripSanity() to not barf on new and creative use of atomicMetadata to implement ripChapters() and ripAngles(). Prep ripFail() to support $videoTitleSet. Fix ripUsage(). Don't call ripFail() when angleList[] is not found in atomicMetadata. TODO: Remove angleList hack from ripFail(). Remove ripOld(), unused and deprecated. Update initBleachBundle(), which still doesn't work (never did?) and might be useless anyway. Remove autotagOld(), unused and deprecated for code duplication (due to previously improved usage of autotagTrack in ripDisc()).

diff --git a/rip b/rip
--- a/rip
+++ b/rip
@@ -49,6 +49,8 @@ function ripAlbum ()
 
 function sanitiseFilePath ()
 # This function should take a string which may not be a valid filesystem path and should produce a valid filesystem path.
+#TODO:FIXME: Implement
+#TODO:FIXME: Move to general package. Shouldn't be in rip package.
 {
     return -1
 }
@@ -66,16 +68,16 @@ function ripDisc ()
     local ALBUM="$(defaultsReadAtomicMetadata "$dvdmedia" Album album)" \
           DISK="$(defaultsReadAtomicMetadata "$dvdmedia" Disc disk)" \
           VOLUME="$(defaultsReadAtomicMetadata "$dvdmedia" Disc UDFVolumeName)" \
-          filepath FILE
 
-    filepath="${ALBUM}/${ALBUM}: Disc ${DISK}"
+    local filepath="./${ALBUM}/${ALBUM}: Disc ${DISK}" \
+          FILE
     #TODO:FIXME: Don't create two subfolders if there's only one disk in the album.
     #TODO:FIXME: Use the name of the "feature" for the subfolder, not merely "disc 2"?
     mkdir -p "./${filepath}"
 
     for title in $(defaultsReadAtomicMetadata "$dvdmedia" Disc trackList)
     do
-        FILE="./${filepath}/${VOLUME}-${title}.m4v"
+        FILE="${filepath}/${VOLUME}-${title}.m4v"
 
         time rip "${dvdmedia}" "$title" "$FILE"
         autotagTrack "${dvdmedia}" "$title" "$FILE"
@@ -90,7 +92,7 @@ function ripDisc ()
         } || test -n "${DEBUG_DISABLE_TAR_INVOCATION:-}" # Workaround: we don't want to "fail" (return non-zero) if we are _deliberately_ skipping tar(1) invocation.
 }
 
-function ripBleach ()
+function ripBleachOld ()
 # ripBleach /path/to/VIDEO_TS/or/parent
 {
 #sanity
@@ -122,7 +124,7 @@ function ripBleach ()
 }
 
 function defaultsReadAtomicMetadatas ()
-# Uses defaultsReadAtomicMetadata() to repeatedly read various atomicMetadataPlists until a value is found for $3
+# Uses defaultsReadAtomicMetadata() to repeatedly read various atomicMetadataPlists in dvdmedia $1, track $2, until a value is found for key $3.
 {
     local dvdmedia="$1"; shift
     local track="$1"; shift
@@ -166,95 +168,22 @@ function defaultsReadAtomicMetadata ()
         # Ignore "does not exist" messages.
 }
 
-function ripTitles ()
-# Invokes rip() on "$1" for each "$@".
-# Uses rip()
-# Uses defaultsReadAtomicMetadatas()
-{
-    echo "ripTitles() is broken." 1>&2
-    return -1
-
-    local dvdmedia="$1"; shift
-    local title
-
-    for title in "$@"
-    do
-#        time ripOld "$dvdmedia" "$(defaultsReadAtomicMetadatas "$dvdmedia" "$title" audioList)" "$title" || return
-        time rip "$dvdmedia" "$title" || return
-                    # `break' here should result in the return value of rip being used as the return value here… but it doesn't seem to…
-    done
-}
-
-function ripAnglesOld ()
-{
-    local RET=0
-    local ANGLE_TITLE ANGLE_TRACK ANGLE
-    local ANGLE_LIST="${1:-}"; shift
-    local angle_track
-    
-    if [ x"$ANGLE_LIST" == x"" ]
-    then
-        rip "$@"
-        return "$?"
-        # Short Circuit
-    fi
-    
-    local TMPIFS="$IFS"; IFS=","
-    for angle_track in $ANGLE_LIST
-    do
-        local RESERVED_SPECIAL_RIP_OPTIONS=( "${SPECIAL_RIP_OPTIONS[@]}" )
-        addRipOptions --angle "${angle_track%:*}"
-
-        IFS="$TMPIFS"
-        
-        rip "$@" "${angle_track#*:}:" || { RET="$?"; break; }
-        # Don't specify any chapters, but specify a name for the chapters.
-        
-        TMPIFS="$IFS"; IFS=","
-        
-        unset SPECIAL_RIP_OPTIONS
-        addRipOptions "${RESERVED_SPECIAL_RIP_OPTIONS[@]}"
-    done
-    IFS="$TMPIFS"
-    unset angle_track TMPIFS
-    
-    return "${RET:-0}"
-}
-
-function ripChapters ()
-# ripChapters /path/to/VIDEO_TS/or/parent 1:English,2:Commentary chapters1:2-4 chapters2:6-9
-{
-    echo "ripChapters() is broken." 1>&2
-    return -1
-
-    local DVD="$1"  ; shift;
-    if test -n "$1"
-    then
-        local AUDIO="$1"
-    fi
-    shift
-    local TITLE_PLACEHOLDER="" # blank; rip() will use longest title
-
-    for chapter in "$@"
-    do
-        time rip "$DVD" "$AUDIO" "$TITLE_PLACEHOLDER" "$chapter" || break # break here should result in the return value of rip being used as the return value here
-    done
-}
-
 function ripSanity () 
+#TODO:FIXME: Merge with ripValidate.
 {
     if ! test -d "${1}/VIDEO_TS"
     then
         echo "rip(): The first argument must be the full path to a DVDMedia bundle." 1>&2
-        echo "       See initDVDMedia()." 1>&2
+        echo "       See ripInit()." 1>&2
         ripUsage
         return -1
     fi
 
-    if test 0 -eq "$2" || test ! 0 -ne "$2"
-    # This test is intended to check whether $2 is an integer.
+    if ( ! ( test 0 -eq "$2" || test 0 -ne "$2" ) 2>/dev/null ) && ! defaultsReadAtomicMetadatas "$1" "$2" videoTitleSet >/dev/null
+    # This test is intended to check whether $2 is an integer, or valid atomicMetadata "track".
     then
         echo "rip(): The second argument must be an integer specifying which title to encode." 1>&2
+        echo "       Or, alternatively, a string indicating where to find out which title to encode from atomicMetadata."
         ripUsage
         return -2
     fi
@@ -276,6 +205,10 @@ function ripFail ()
     else if [ x"$1" == x"HandBrakeCLI" ]
     then
         echo "rip(): HandBrake has failed to complete successfully." 1>&2
+    else if [ x"$1" == x"HandBrakeCLI" ]
+    then
+        echo "rip(): HandBrake has failed to complete successfully." 1>&2
+    fi
     fi
     fi
     fi
@@ -332,7 +265,7 @@ function ripParseAudioTracks ()
 
 function ripUsage () 
 {
-    echo "Usage: rip /path/to/DVD_VIDEO.dvdmedia 2 [ep1:1-4]" 1>&2
+    echo "Usage: rip /path/to/DVD_VIDEO.dvdmedia 2 /path/to/file.m4v" 1>&2
 }
 
 function rip ()
@@ -373,7 +306,7 @@ function rip ()
         #TODO:FIXME: Implement.
     local subtitleTracks="$(ripParseAudioTracks "$subtitleList")" || ripFail "ripParseAudioTracks" "subtitle" || return
 
-    local angleList="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" angleList)" || ripFail "angleList" || return
+    local angleList="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" angleList)" #|| ripFail "angleList" || return # angleList is not required
     local angleNames="$(ripParseAudioNames "$angleList")" || ripFail "ripParseAudioNames" "angle" || return
         # Unused.
         #TODO:FIXME: Implement.
@@ -382,11 +315,11 @@ function rip ()
         #TODO:FIXME: Implement.
         # Most likely, the entire rip() will need to be looped in order to accomplish this.
 
-    #addRipOptions "" #TODO:FIXME: Generate a list of args similarly to autotagTrack. Avoid code duplication? 
-
-    local videoTitleSet="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" videoTitleSet)"
+    local videoTitleSet="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" videoTitleSet)" #|| ripFail "videoTitleSet" || return
         # This is intended to allow atomicMetadata to override the track/title number in order to allow ripBleach() et al to treat various sets of sub-chapters as distinct titles. 
             # For whatever reason, Anime titles (such as Bleach or Armitage III (OVA)) squeeze separate episodes together into a single title/track, thereby requiring special parsing/processing in order to split them.
+
+    #addRipOptions "" #TODO:FIXME: Generate a list of args similarly to autotagTrack. Avoid code duplication? 
 
 #Do it
     local RIPLOG=~/Library/Logs/net.gaelicWizard.rip/"$DVDNAME".log
@@ -464,173 +397,6 @@ function ripGrowl ()
         --identifier "net.gaelicWizard.rip${IDENT:+.}${IDENT:-}"
 }
 
-function ripOld ()
-# rip /path/to/VIDEO_TS/.. 1:English,2:Commentary title7 chapters1:2-4
-{
-##TODO: Subtitles. Goal: Star Wars prequels show subtitles during appropriate scenes. Use --subtitle-forced and/or --native-language.
-
-
-#Process arguments
-    local DVD="${1:-/dev/null}"
-        # The path to the VIDEO_TS folder or its parent
-    local AUDIO_LIST="${2:-}"
-        # Which audio tracks to encode. If unspecified, may be inherited.
-    local TITLE="${3:-}"
-        # Which title to rip. If unspecified, then the longest title is used.
-    local CHAPLIST="${4:-}"
-        # NOT HANDBRAKE's FORMAT. TODO:FIXME:document
-    
-    function ripUsage ()
-    # nested function FTW
-    {
-        echo "rip /path/to/DVD 1:English,2:Commentary 7 ep3:2-4" 1>&2
-    }
-
-    if ! [ -d "$DVD/VIDEO_TS" ]
-    then
-        echo "Please specify the path to the DVD (parent of VIDEO_TS) as the first argument." 1>&2
-        ripUsage
-        return -1
-    fi
-    
-    if test -z "${AUDIO_LIST:-}" && test -z "${AUDIO:-}"
-    then
-        echo "Please specify the audio track list as the second argument." 1>&2
-        ripUsage
-        return -2
-    fi
-    
-    #TODO:FIXME: More sanity checks
-
-#Derive settings from arguments, where needed
-    local DVDNAME="$(basename "$DVD" .dvdmedia)"
-    local CHAPTITL="${CHAPLIST%:*}"
-        # What "title" to call this chapter-set
-    local CHAPTERS="${CHAPLIST#*:}"
-        # What chapters to rip
-        # TODO: FIXME: Tested, but unverified
-    if [ "${FEATURE:--1}" -eq "${TITLE:-0}" ]
-    then
-        local DVDNAMEWITHTITLEBUTNOTCHAPTER="$DVDNAME"
-        local TRACK=
-        #TODO:FIXME:HACK for --longest specified as --title X
-    else
-        local DVDNAMEWITHTITLEBUTNOTCHAPTER="${DVDNAME}${TITLE:+-}${TITLE}"
-        local TRACK="${TITLE:-}"
-    fi
-    local DVDNAMEWITHTITLE="${DVDNAMEWITHTITLEBUTNOTCHAPTER}${CHAPTITL:+-}${CHAPTITL}"
-        # What's the name-track-chapterset of this disc?
-    local TRACK="${CHAPTITL:-$TRACK}"
-        # TODO:FIXME: Might cause a problem when CHAPTITL isn't numeric
-    local AUDIO="${AUDIO:-1,2,3,4,5,6,7,8}"
-        # Which audio tracks to encode, see HandBrakeCLI(1), defaulting to all.
-        # This will always fail, unless the DVD has all 8 audio tracks, since HandBrake crashes when asked to encode a non-existent track.
-        # Inherit a pre-specified $AUDIO, if available.
-    local audio_track
-    local TMPIFS="$IFS"; IFS=","
-    for audio_track in $AUDIO_LIST
-    do
-        local AUDIO_TITLES="${AUDIO_TITLES:-}${AUDIO_TITLES:+,}${audio_track#*:}"
-            # What "title" to call this audio track
-        local AUDIO_TRACKS="${AUDIO_TRACKS:-}${AUDIO_TRACKS:+,}${audio_track%:*}"
-            # What audio tracks to encode
-            # TODO: FIXME: Untested
-        local AUDIO="$AUDIO_TRACKS"
-    done
-    IFS="$TMPIFS"
-    unset audio_track TMPIFS
-    local FILE="${DVDNAMEWITHTITLE}.m4v"
-#    local FILE="${HOME}/Movies/HandBrake/${DVDNAMEWITHTITLE}.m4v"
-        # Where to save the output. Store it in ~/Movies/HandBrake with the name of $DVD.
-        # Use HandBrake's naming convention, extending it for chapters.
-
-#Derive constants
-    local MARKERS="${DVD}/chapters${TITLE:+-}${TITLE:-}.txt"
-        # /path/to/DVD/chapters/list/in/CSV
-    local AUDIO_ENC="$(IFS=,; for i in $AUDIO; do echo -n ca_aac,; done)"
-        # This is, sadly, necessary to work around a bug in HandBrake which will duplicate the last track specified in $AUDIO to until all eight tracks are filled. Bug filed and rejected. :-/
-
-#Do it
-    local RIPLOG=~/Library/Logs/net.gaelicWizard.rip/"$DVDNAME".log
-    local RET=0
-    test -z "${DEBUG_DISABLE_HANDBRAKE_INVOCATION:-}" && (
-        test -e "$FILE" && del "$FILE"; \
-        set -x; \
-    exec HandBrakeCLI -v"${HANDBRAKE_DEBUG_LEVEL:-1}" \
-        --preset "Universal" \
-        --input "$DVD" \
-        "${TITLE:+--title}" "${TITLE:---longest}" \
-        "${CHAPTERS:+--chapters}" "${CHAPTERS:-}" \
-        --previews 30 \
-        --output "$FILE" \
-        --markers"${MARKERS:+=}${MARKERS:-}" \
-        --ipod-atom \
-        --detelecine \
-        --vfr \
-        --audio "$AUDIO" \
-        --aencoder "$AUDIO_ENC" \
-        "${AUDIO_TITLES:+--aname}" "${AUDIO_TITLES:-}" \
-        "${SPECIAL_RIP_OPTIONS[@]}" \
-    2>> "$RIPLOG" ) || RET="$?"
-        # Universal preset to activate sensible defaults.
-        # Use the longest title, if none specified.
-        # Only encode selected chapters, if specified.
-        # Generate 30 previews, b/c I hope it will improve autocropping.
-            # The number of previews generated is related to the accuracy of the autocropper, but seemingly only two previews are used.
-        # Import chapter titles from CSV file, if available.
-        # iPod atom, so that 5.5G iPods will accept the media.
-        # Detelecine, always. Unclear why HandBrake doesn't just do this.
-            # HandBrake documentation for the framerate setting implies that HandBrake does, in fact, detelecine by default, but it lies.
-        # Variable Frame Rate is the default, but didn't used to be.
-            # This option disappeared _completely_ during 0.9.3
-        # Enable selected audio tracks from the DVD.
-        # Encode them all to AAC, accepting default Dolby Pro Logic 2 encoding.
-            # AAC is the default, so this line might be entirely unneeded.
-            # However, the Universal preset duplicates track 1 to track 2 as pass-thru "AC-3", so it might be needed to _return_ to defaults. TODO: Untested, actually.
-        # Name the selected audio tracks, e.g. "Director's Commentary".
-        # Add any special out-of-band flags to HandBrake, such as "--crop 0:0:0:0" or "--grayscale".
-    echo # Blank line.
-    du -sh "$RIPLOG"
-        # Check the size of the log file.
-        # Once, a successful rip produced a 15 GB log file due to excessive duplicate non-fatal errors.
-
-    if [ "${RET:-0}" -ne 0 ]
-    then
-        return "$RET"
-    fi
-
-    if [ -e "$FILE" ]
-    then
-        #Tweet about it
-        if [ -z "${DO_NOT_TWEET_RIPS:-}" ] && [ "${FEATURE:--1}" -eq "${TITLE:-0}" ]
-        then
-            updateStatus.sh "encoded ${NAME[$TITLE]:-}." &
-        fi
-    
-    growlnotify \
-            --name "rip()" \
-            --title "Encode Complete" \
-            --message "${NAME[$TITLE]:-$DVDNAME} encoded to $(basename "${FILE}")." \
-            --appIcon /Applications/HandBrake.app \
-            --sticky \
-            --identifier net.gaelicWizard.rip
-    
-        if test "${TITLE:--1}" -eq "${FEATURE:-0}"
-        then
-            TRACK=
-            # Don't embed the track number if this is "the" [only] movie on the disc.
-        fi
-        
-        #Tag some basic housekeeping
-        tag "${FILE}" --album "$DVDNAME" "${TRACK:+--track}" "$TRACK"
-    else
-        echo "$FUNCNAME: ${FILE} does not appear to have been created." 1>&2
-        return -2
-    fi
-    
-    addRipOptions # If any SPECIAL_RIP_OPTIONS are set, then issue a warning.
-}
-
 function tag ()
 # Just a tiny wrapper around AtomicParsley(1)
 {
@@ -659,7 +425,7 @@ function addRipOptions ()
 
 function initBleachBundle ()
 # This function takes one argument: (1) the path to a DVDMedia bundle whose name begins with "Bleach", which is presumed to be a volume in the Bleach anime series. An atomicMetadataShow.plist is copied in, an a chapters list is symlink'd in.
-# Uses initDVDMedia()
+# Uses ripInit()
 {
     if [ x"${1:0:6}" != x"Bleach" ]
     then
@@ -667,7 +433,7 @@ function initBleachBundle ()
         return -1
     fi
 
-    initDVDMedia "$1"
+    ripInit "$1"
 
     ln -s "../Bleach.chapters" "$1"/chapters-1.txt
 
@@ -747,24 +513,6 @@ function ripInit ()
     HandBrakeCLI -v0 -i "$dvdmedia" -t 0 2>&1 | uniq > "$dvdmedia/titleScan.txt"
         # Ask HandBrake to scan all available titles on the disk.
         # This gathers useful information like length, available audio/subtitle tracks, angles, &c.
-}
-
-function autotagOld ()
-# This function takes one argument: (1) the path to a DVDMedia bundle (which has been initDVDMedia()'d). defaultsReadAtomicMetadata() reads a list of tracks (which should have been already encoded). autoTagTrack() is then invoked for each track using file names generated from the DVDMedia bundle file name.
-# Uses autoTagTrack()
-# Uses defaultsReadAtomicMetadata()
-#TODO:FIXME: Should not auto-generate the file name. 
-{
-    local dvdmedia="$1"
-    local trackList="$(defaultsReadAtomicMetadata "$dvdmedia" Disc trackList)" \
-          #DVDNAME="$(basename "$dvdmedia" .dvdmedia)" # ripOld().
-          DVDNAME="$(defaultsReadAtomicMetadatas "$dvdmedia" "$whichTrack" UDFVolumeName)" || ripFail "UDFVolumeName" # newRip().
-
-    local aTrack
-    for aTrack in $trackList
-    do
-        autotagTrack "$dvdmedia" "$aTrack" "$DVDNAME-$aTrack.m4v" || return
-    done
 }
 
 function autotagTrack ()
